name: Generate and Deploy Data

on:
  push:
    branches: [ main ]
    paths: 
      - 'utils/download_and_preprocess_datasets.py'
      - '.github/workflows/generate-data.yml'
  workflow_dispatch:  # Allow manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn
        
    - name: Generate data files
      run: |
        python utils/download_and_preprocess_datasets.py
        
    - name: Create data archive
      run: |
        tar -czf data/california-housing-data.tar.gz data/*.csv
        
    - name: Create index page
      run: |
        cat > data/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>California Housing Dataset</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
                .download-section { background: #f8f9fa; padding: 1.5rem; border-radius: 8px; margin: 1rem 0; }
                .file-list { list-style: none; padding: 0; }
                .file-list li { margin: 0.5rem 0; }
                .file-list a { text-decoration: none; color: #0366d6; font-weight: 500; }
                .file-list a:hover { text-decoration: underline; }
                .size { color: #586069; font-size: 0.9em; }
                pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
                code { background: #f6f8fa; padding: 0.2rem 0.4rem; border-radius: 3px; font-size: 0.9em; }
            </style>
        </head>
        <body>
            <h1>🏠 California Housing Dataset</h1>
            <p>Generated California Housing dataset files for machine learning projects.</p>
            
            <div class="download-section">
                <h2>📥 Download Files</h2>
                <ul class="file-list">
                    <li><a href="california_housing.csv">california_housing.csv</a> <span class="size">(~1.8MB, 20,640 rows)</span></li>
                    <li><a href="california_housing_train.csv">california_housing_train.csv</a> <span class="size">(~1.8MB, 16,512 rows)</span></li>
                    <li><a href="california_housing_test.csv">california_housing_test.csv</a> <span class="size">(~449KB, 4,128 rows)</span></li>
                    <li><a href="california-housing-data.tar.gz">california-housing-data.tar.gz</a> <span class="size">(All files archived)</span></li>
                </ul>
            </div>
            
            <h2>🔗 Quick Access URLs</h2>
            <pre><code>wget https://codesignal-learn.github.io/course_building-aws-sagemaker/california_housing_train.csv
        wget https://codesignal-learn.github.io/course_building-aws-sagemaker/california_housing_test.csv
        wget https://codesignal-learn.github.io/course_building-aws-sagemaker/california-housing-data.tar.gz
        tar -xzf california-housing-data.tar.gz</code></pre>
            
            <h2>📊 Dataset Information</h2>
            <p><strong>Source:</strong> Scikit-learn California Housing Dataset</p>
            <p><strong>Target:</strong> Median house value prediction</p>
            <p><strong>Split:</strong> 80% train / 20% test (random_state=42)</p>
            
            <h3>Features</h3>
            <ul>
                <li><strong>Original (9 features):</strong> MedInc, HouseAge, AveRooms, AveBedrms, Population, AveOccup, Latitude, Longitude, MedHouseVal</li>
                <li><strong>Train/Test (10 features):</strong> Original features + RoomsPerHousehold (engineered feature)</li>
                <li><strong>Preprocessing:</strong> Values capped at 95th percentile (excluding coordinates)</li>
            </ul>
            
            <footer style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e1e4e8; color: #586069; font-size: 0.9em;">
                <p>Generated automatically via GitHub Actions • <a href="https://github.com/CodeSignal-Learn/course_building-aws-sagemaker">View Repository</a></p>
            </footer>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './data'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 